# https://numtide.github.io/devshell
[[commands]]
category = "development"
name = "jup"
help = "Jupyter notebook for testing code fast"
command = "jupyter-lab --ip 0.0.0.0"

[[commands]]
category = "environment"
package = "sops"

[[commands]]
category = "environment"
package = "kubectl"

[[commands]]
category = "development"
package = "poetry"

[[commands]]
category = "data"
command = '''
podman pull quay.io/projectnessie/nessie-cli:0.99.0
podman run -it quay.io/projectnessie/nessie-cli:0.99.0
'''
name="nessie-cli"
help="Project Nessie: Transactional Catalog for Data Lakes with Git-like semantics, use `Nessie> connect to https://nessie.local.reinthal.cc/api/v2` to connect."


[[commands]]
category = "data"
command = '''
kubectl port-forward -n trino service/trino-cluster-trino 27015:8080  1>/dev/null &
harlequin -a trino -h localhost -p 27015 -U trino
pkill kubectl -9
'''
name='sql'
help = "Connect to Trino sql server"

[[commands]]
category = "development"
name = "dev"
help = "run `dagster dev`"
command = "dagster dev"



[devshell]
name = "howigotpwned"
motd = '''
{bold}{14}
.__                      .___   ________           __   __________                              .___
|  |__    ____  __  _  __|   | /  _____/   ____  _/  |_ \______   \__  _  __  ____    ____    __| _/
|  |  \  /  _ \ \ \/ \/ /|   |/   \  ___  /  _ \ \   __\ |     ___/\ \/ \/ / /    \ _/ __ \  / __ | 
|   Y  \(  <_> ) \     / |   |\    \_\  \(  <_> ) |  |   |    |     \     / |   |  \\  ___/ / /_/ | 
|___|  / \____/   \/\_/  |___| \______  / \____/  |__|   |____|      \/\_/  |___|  / \___  >\____ | 
     \/                               \/                                         \/      \/      \/ 

{reset}
$(type -p menu &>/dev/null && menu)
'''

packages = [
 "unrar",
 "zip",
 "unzip"
]
