name: Continuous Delivery

on:
  push:
    branches:
      - "main"

env:
  SOURCE_PATH: "./."
  DOCKER_IMAGE: "dagster"
  DOCKERFILE: "./Dockerfile"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Check if product critical files have been modified
  check_source_file_change:
    name: "Check source file changes"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      file_changes: ${{ steps.filter.outputs.source }}
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.SOURCE_PATH }}
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            source:
              - './dagster_tests/**'
              - './dagster_project/**'
              - './pyproject.toml'
              - './poetry.lock'
  bump_version:
    name: "Bump version"
    runs-on: ubuntu-latest
    needs: check_source_file_change
    # If statement that will run the job only when:
    # - the commit message does not start with 'bump:'
    # - source files have been modified i.e. files in folders used by Dockerfile
    if: ${{ !startsWith(github.event.head_commit.message, 'bump:') && needs.check_source_file_change.outputs.file_changes == 'true' }}
    outputs:
      cz_version: ${{ steps.cz.outputs.version }}
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: "${{ secrets.GITHUB_TOKEN }}"
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Seriously Print New version
        run: echo "Version Uplifted! ${{ steps.cz.outputs.version }}"

  # Build and push image on docker registry. Executed only if source files have changed
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - check_source_file_change
      - bump_version
    if: "${{ needs.check_source_file_change.outputs.file_changes == 'true' }}"
    strategy:
      fail-fast: false
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.DOCKER_IMAGE }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.bump_version.outputs.cz_version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ${{ env.DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
